# Generated by Django 5.2.16 on 2026-07-22 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organisation_name", models.CharField(max_length=180)),
                ("system_name", models.CharField(max_length=180)),
                ("intended_purpose", models.TextField()),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("development", "Development"),
                            ("pilot", "Pilot"),
                            ("operation", "Operation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organisation_role",
                    models.CharField(
                        choices=[
                            ("provider", "AI system provider"),
                            ("deployer", "AI system deployer"),
                            ("both", "Provider and deployer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("in_review", "In review"), ("completed", "Completed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("version", models.CharField(max_length=40)),
                ("source_url", models.URLField()),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegulatoryReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=50)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="assessments.assessment"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="assessments.framework",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("text", models.TextField()),
                ("guidance", models.TextField(blank=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "references",
                    models.ManyToManyField(blank=True, related_name="questions", to="assessments.regulatoryreference"),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.requirement",
                    ),
                ),
            ],
            options={
                "ordering": ["requirement__sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("partial", "Partly"),
                            ("no", "No"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField()),
                ("evidence_reference", models.CharField(blank=True, max_length=300)),
                ("owner", models.CharField(blank=True, max_length=180)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="responses", to="assessments.question"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(fields=("framework", "code"), name="unique_framework_requirement"),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(fields=("assessment", "question"), name="unique_assessment_response"),
        ),
    ]
