# Generated by Django 5.2.16 on 2026-07-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="rationale",
            field=models.TextField(blank=True),
        ),
    ]
